DROP DATABASE IF EXISTS proj1;
CREATE DATABASE proj1;
USE proj1;

CREATE TABLE article (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  subject CHAR(100) NOT NULL UNIQUE,
  content TEXT,
  memberId INT UNSIGNED NOT NULL, -- FK 선언 없음
  boardType CHAR(20) NOT NULL,
  regDate DATETIME NOT NULL DEFAULT NOW(),
  created_date DATETIME NOT NULL DEFAULT NOW(),
  modified_date DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW()
);


SELECT * FROM article;

CREATE TABLE member (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId CHAR(100) NOT NULL UNIQUE,
  password CHAR(100) NOT NULL,
  regDate DATETIME NOT NULL DEFAULT NOW(),
  created_date DATETIME NOT NULL DEFAULT NOW(),
  modified_date DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

ALTER TABLE article MODIFY boardType CHAR(20) NOT NULL DEFAULT 'free';

SELECT * FROM member;
